# environment:
#   groups:
#     - firebase_credentials

# scripts:
# - name: Load Firebase configuration
#   script: | 
#     #!/usr/bin/env sh
#     set -e # exit on first failed command

#     echo $IOS_FIREBASE_SECRET > $CM_BUILD_DIR/ios/Runner/GoogleService-Info.plist

workflows:
  my-workflow:
    name: My workflow name
    # labels:
    #   - QA
    #   - ${TENANT_NAME}
    # instance_type: mac_mini_m1
    # max_build_duration: 60
    environment:
      groups:
        - firebase_credentials
    #   vars:
    #     PUBLIC_ENV_VAR: "value here"
    #   flutter: stable
    #   xcode: latest
    # cache:
    #   cache_paths:
    #     - ~/.pub-cache
    # triggering:
    #   events:
    #     - push
    #   branch_patterns:
    #     - pattern: '*'
    #       include: true
    #       source: true
    #   cancel_previous_builds: false
    scripts:
    - name: Load Firebase configuration
      script: | 
        #!/usr/bin/env sh
        set -e # exit on first failed command

        echo $IOS_FIREBASE_SECRET > $CM_BUILD_DIR/ios/Runner/GoogleService-Info.plist