// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX_VGSBOGFNgnuACoOb1sK4qCI5L6V5GY',
    appId: '1:617527301932:web:07cd2084d30c5b8c31be89',
    messagingSenderId: '617527301932',
    projectId: 'mijnzpc-4911f',
    authDomain: 'mijnzpc-4911f.firebaseapp.com',
    storageBucket: 'mijnzpc-4911f.appspot.com',
    measurementId: 'G-2NJS8Y2Z8B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHhaRxkFjF3rNFe-S3RP04A7JBo5QaICo',
    appId: '1:617527301932:android:78a4317a1ab6bfa031be89',
    messagingSenderId: '617527301932',
    projectId: 'mijnzpc-4911f',
    storageBucket: 'mijnzpc-4911f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI9zi6QjieFVkdIqxQDn_F0KZDugQE6iM',
    appId: '1:617527301932:ios:06deefadea63dbba31be89',
    messagingSenderId: '617527301932',
    projectId: 'mijnzpc-4911f',
    storageBucket: 'mijnzpc-4911f.appspot.com',
    iosBundleId: 'com.app.mijnzpc',
  );
}
